# Generated by Django 5.0.3 on 2024-03-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '질문', 'verbose_name_plural': '질문'},
        ),
    ]
