# Generated by Django 5.0.3 on 2024-03-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': '답변', 'verbose_name_plural': '답변'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id'], 'verbose_name': '질문', 'verbose_name_plural': '질문'},
        ),
    ]
