# Generated by Django 5.0.3 on 2024-03-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
